scan_timeout = 10

[character]
format = '\$ '
error_symbol = "[✗](bold red)"
success_symbol = "[❯](bold green)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"

[aws]
disabled = true
symbol = " "
style = "bold #FF9900"
format = '[$symbol($profile) (\($region\) )]($style) '

[gcloud]
# disabled = true
symbol = "️ "
style = "bold #1B73E7"
format = '[$symbol($project) (\($region\) )]($style) '

[docker_context]
detect_folders = ["./"]

[git_branch]
truncation_length = 4
format = "on [$symbol$branch(:$remote_branch)]($style) "

[username]
disabled = true
style_user = "white bold"
style_root = "black bold"
format = "[$user🌱]($style) "

