cask_args appdir: "/Applications"

# ==================================================================
# CLI commands
# ==================================================================
# Basic commands
brew "git"
brew "gh"
brew "pre-commit"
brew "vim"
brew "neovim"
brew "zsh"
brew "gawk"
brew "gnu-sed"
brew "tree"
brew "wget"
brew "openssh"
brew "go-task"
brew "gitmoji"     # git commitするときの絵文字一覧
brew "git-secrets" # credentialファイルをgit commitしないようにする
brew "peco"        # 高度な検索
brew "xz"          # ファイル圧縮
brew "glow"        # ターミナルでMarkdownをプレビュー
brew "tig"         # Gitリポジトリの履歴確認
brew "shellcheck"  # Shell Scirptの静的解析
# brew "starship"    # zshのプロンプトのカスタマイズ

# Substitution of basic commands
# https://zenn.dev/the_exile/articles/5176b7a5c29bce
brew "zoxide"    # `cd`
brew "lsd"       # `ls`
brew "fd"        # `find`
brew "bat"       # `cat`
brew "ripgrep"   # `grep`
brew "httpie"    # `curl``
brew "procs"     # `ps`
brew "bottom"    # `top`
brew "duf"       # `df`
brew "dust"      # `du`
brew "trash-cli" # `rm`

# Virtual environment / Version manager
brew "mise"

# Python
brew "uv"
# brew "pipx"

# Public clouds' CLI command
## Google Cloud
## https://zenn.dev/phi/articles/gcloud-setup-with-homebrew-on-mac
cask "google-cloud-sdk"

## AWS
## https://zenn.dev/akakuro/articles/30f570b8863bef
brew "awscli"

## Azure
## https://learn.microsoft.com/ja-jp/cli/azure/install-azure-cli-macos
# brew "azure-cli"

# たわらさんのフォントシリーズ
# https://github.com/yuru7/HackGen
cask "font-hack-nerd-font"
cask "font-plemol-jp"

#==================================================================
# Desktop applications
# ==================================================================
# Browser
cask "brave-browser"
cask "chatgpt-atlas"

# Text editor
cask "visual-studio-code"
cask "cursor"

# AI
cask "claude"
cask "claude-code"
cask "chatgpt"
cask "codex"

# Infrastructure
cask "google-drive"
cask "google-japanese-ime"
cask "azooKey" # 公式のGitHubのREADMEだと brew で入れるようになっているが、正しくは cask で入れる
cask "karabiner-elements"
cask "raycast"
cask "zoom"
cask "android-platform-tools"

# Programming
# cask "docker"
cask "rancher"  # Docker Desktop とコンフリクトするのでどっちかにする
cask "ghostty"
# cask "lm-studio"
# cask "tableplus"

# Sound
cask "mp3gain-express"
cask "blackhole-2ch"

# Usefulls
cask "alt-tab"
cask "funter"
cask "keyboardcleantool"
cask "obsidian"
cask "spotify"
# cask "cold-turkey-blocker"
# cask "tunnelblick"
# cask "microsoft-remote-desktop"
cask "aqua-voice"

# Entire (AIエージェントのセッションをgitと連携して記録)
# https://github.com/entireio/cli
tap "entireio/tap"
brew "entireio/tap/entire"

# DroidDock
tap "rajivm1991/droiddock"
cask "rajivm1991/droiddock/droiddock"

